/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.ParticipanteDB;
import dao.SorteioDB;
import dao.SorteioParticipanteDB;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import model.Participante;
import model.Sorteio;

/**
 *
 * @author marcio
 */
public class EditSorteio extends javax.swing.JFrame {

    
    Integer id;
    ArrayList<JCheckBox> boxes = new ArrayList<>();
    ArrayList<Integer> participantesAtuais = new ArrayList<>();
    SorteioParticipanteDB spdb = new SorteioParticipanteDB();
    SorteioDB sorteioDB = new SorteioDB();
    Sorteio sorteio;
    
    /**
     * Creates new form EditSorteio
     */
    public EditSorteio(int id) {
        initComponents();
        this.id = id;
        this.sorteio = this.sorteioDB.selectOne(id);
        this.spdb.selectAllFromSorteio(this.sorteio);
        this.addParticipantes();
        this.nomeTextField.setText(this.sorteio.getNome());
    }
    
    public EditSorteio() {
        initComponents();
        this.sorteio = new Sorteio();
        this.addParticipantes();
    }
    
    private void addParticipantes() {
        ParticipanteDB db = new ParticipanteDB();
        ArrayList<Participante> parts = db.selectAll();
        
        for (Participante p:parts) {
            JCheckBox box = new JCheckBox(p.getNome());
//            box.setText(p.getNome());
//            box.setActionCommand(String.valueOf(p.getId()));;
            box.setSelected(this.participantesAtuais.contains(p.getId()));
            box.setVisible(true);
            this.boxes.add(box);
            this.participantesPanel.add(box);
        }
        
        this.participantesPanel.setVisible(true);
        this.participantesPanel.revalidate();
        this.participantesPanel.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        participantesPanel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        salvarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout participantesPanelLayout = new javax.swing.GroupLayout(participantesPanel);
        participantesPanel.setLayout(participantesPanelLayout);
        participantesPanelLayout.setHorizontalGroup(
            participantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(participantesPanelLayout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addGap(0, 124, Short.MAX_VALUE))
        );
        participantesPanelLayout.setVerticalGroup(
            participantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, participantesPanelLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jCheckBox1))
        );

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(participantesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salvarButton)))
                .addContainerGap(446, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(participantesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(salvarButton)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        this.sorteio.setNome(this.nomeTextField.getText());
        
        int sorteioId;
        
        if (this.id != null) {
            this.sorteioDB.update(this.sorteio);    
            sorteioId = sorteio.getId();
        } else {
            sorteioId = this.sorteioDB.insert(this.sorteio);       
        }
        
        System.out.println(sorteioId);
        
        
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_salvarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSorteio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JPanel participantesPanel;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
